### ISSUE TITLE
Missing jgoodies

### ISSUE THREAD

**Issue by NoMan2000** [egomezal/irpgeditor#6]
Windows 10, JDK 9.0.4, java 9.0.4.

Running `java -jar iRPGEditor.jar` gave me this error:
```sh
java.lang.NoClassDefFoundError: com/jgoodies/looks/plastic/PlasticTheme
```
I see the jgoodies in your maven file, so I'm not sure what happened.

**Comment by cesardarinel** [comment]
Currently it is only available for Java 8.
version 9 is not an LTS version, sure we will jump to 11.

If you can try with version 8

**Comment by cesardarinel** [comment]
> Windows 10, JDK 9.0.4, java 9.0.4.
> 
> Running `java -jar iRPGEditor.jar` gave me this error:
> 
> ```shell
> java.lang.NoClassDefFoundError: com/jgoodies/looks/plastic/PlasticTheme
> ```
> 
> I see the jgoodies in your maven file, so I'm not sure what happened.
> 
> Full stack:
> 
> ```shell
> Exception in thread "main" java.lang.NoClassDefFoundError: com/jgoodies/looks/plastic/PlasticTheme
>         at java.base/java.lang.Class.forName0(Native Method)
>         at java.base/java.lang.Class.forName(Unknown Source)
>         at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
> Caused by: java.lang.ClassNotFoundException: com.jgoodies.looks.plastic.PlasticTheme
>         at java.base/java.net.URLClassLoader.findClass(Unknown Source)
>         at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
> ```

Currently it is only available for Java 8.
version 9 is not an LTS version, sure we will jump to 11.

If you can try with version 8
